'use server';

/**
 * @fileOverview An AI agent to generate a dashboard of key performance indicators (KPIs).
 *
 * - generateInsightsDashboard - A function that generates the dashboard content.
 * - GenerateInsightsDashboardInput - The input type for the generateInsightsDashboard function.
 * - GenerateInsightsDashboardOutput - The return type for the generateInsightsDashboard function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateInsightsDashboardInputSchema = z.object({
  paymentCompliance: z.number().describe('The percentage of customers who are compliant with their payments.'),
  systemUptime: z.number().describe('The percentage of time the system is operational.'),
  customerChurnRate: z.number().describe('The rate at which customers are leaving the service.'),
  overallRevenue: z.number().describe('The total revenue generated by the service in KES.'),
});
export type GenerateInsightsDashboardInput = z.infer<typeof GenerateInsightsDashboardInputSchema>;

const GenerateInsightsDashboardOutputSchema = z.object({
  dashboardContent: z.string().describe('A comprehensive dashboard of KPIs including payment compliance, uptime, churn, and revenue.'),
});
export type GenerateInsightsDashboardOutput = z.infer<typeof GenerateInsightsDashboardOutputSchema>;

export async function generateInsightsDashboard(input: GenerateInsightsDashboardInput): Promise<GenerateInsightsDashboardOutput> {
  return generateInsightsDashboardFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateInsightsDashboardPrompt',
  input: {schema: GenerateInsightsDashboardInputSchema},
  output: {schema: GenerateInsightsDashboardOutputSchema},
  prompt: `You are an expert financial analyst AI assistant tasked with generating a summary report of key performance indicators (KPIs) for BrightEco Pay.

  The dashboard should provide a quick and easy way for administrators to understand the current business state and make informed decisions.

  The KPIs to include are:
  - Payment Compliance: {{paymentCompliance}}%
  - System Uptime: {{systemUptime}}%
  - Customer Churn Rate: {{customerChurnRate}}%
  - Overall Revenue: KES {{overallRevenue}}

  Generate a comprehensive summary report using the above KPIs. Be concise, clear, and actionable. Focus on insights and trends that can help improve the business. Provide a bulleted list of recommendations.`,
});

const generateInsightsDashboardFlow = ai.defineFlow(
  {
    name: 'generateInsightsDashboardFlow',
    inputSchema: GenerateInsightsDashboardInputSchema,
    outputSchema: GenerateInsightsDashboardOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
